import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
    <style jsx>
      {`
        h2{
          font-size: 38px;
        }
        h3{
          font-size: 28px;
        }
      `}
    </style>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script src='/sc.js' strategy='lazyOnload'></Script> */}
      

      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          
          <div className={styles.center}>
          {/* <Image className={styles.myImg} src="/istockphoto-1439425791-1024x1024.jpg" width={237} height={158} /> */}
          </div>
        </div>

        <div className={styles.center}>
          
        <h1 className={styles.logo}>Hunting Coder</h1>
          <p className={styles.description}>A blog for hunting coders by a hunting coder</p>
        </div>

        <div className={styles.imagewrap}>
        <Image className={styles.myImg} src="/istockphoto-1439425791-1024x1024.jpg" width={237} height={158} />
        </div>

      <div>
          <h2>Latest blogs</h2> <br/>
          <div className="blogItem">
            <h3>How to learn javascript in 2024?</h3>
            <p>Javascript is the language used to design logic for the web </p>
          </div>
      </div>

      </main>
    </>
  );
}
